export const TASK_CONSTRAINTS = {
  TITLE_MAX_LENGTH: 50,
  TITLE_MIN_LENGTH: 1,
  DESCRIPTION_MAX_LENGTH: 1000,
  DESCRIPTION_MIN_LENGTH: 0,
  MAX_TAGS_COUNT: 5,
  MAX_CUSTOM_TAGS_COUNT: 5,
  MAX_CUSTOM_TAGS_LENGTH: 20,
} as const;
